### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by zeke** [egoist/package-size#7]
```
❯ package-size mocha

  package  size  minified  minified+gzipped
  mocha    ...   ...       ...


 ERROR  Compiled with errors!

Error: 
WARNING in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
153:20-37 Critical dependency: the request of a dependency is an expression

WARNING in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
185:17-30 Critical dependency: the request of a dependency is an expression

WARNING in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
222:26-39 Critical dependency: the request of a dependency is an expression

ERROR in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/growl/lib/growl.js
Module not found: Error: Can't resolve 'child_process' in '/private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/node_modules/growl/lib'
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/growl/lib/growl.js 7:11-35
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/growl/lib/growl.js
Module not found: Error: Can't resolve 'fs' in '/private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/node_modules/growl/lib'
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/growl/lib/growl.js 8:9-22
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/buffer/index.js
Module not found: Error: Can't resolve 'base64-js' in '/Users/zeke/.config/yarn/global/node_modules/buffer'
 @ /Users/zeke/.config/yarn/global/~/buffer/index.js 11:13-33
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/utils.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/buffer/index.js
Module not found: Error: Can't resolve 'ieee754' in '/Users/zeke/.config/yarn/global/node_modules/buffer'
 @ /Users/zeke/.config/yarn/global/~/buffer/index.js 12:14-32
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/utils.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/buffer/index.js
Module not found: Error: Can't resolve 'isarray' in '/Users/zeke/.config/yarn/global/node_modules/buffer'
 @ /Users/zeke/.config/yarn/global/~/buffer/index.js 13:14-32
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/utils.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/stream-browserify/index.js
Module not found: Error: Can't resolve 'readable-stream/readable.js' in '/Users/zeke/.config/yarn/global/node_modules/stream-browserify'
 @ /Users/zeke/.config/yarn/global/~/stream-browserify/index.js 28:18-56
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/browser-stdout/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/stream-browserify/index.js
Module not found: Error: Can't resolve 'readable-stream/writable.js' in '/Users/zeke/.config/yarn/global/node_modules/stream-browserify'
 @ /Users/zeke/.config/yarn/global/~/stream-browserify/index.js 29:18-56
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/browser-stdout/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/stream-browserify/index.js
Module not found: Error: Can't resolve 'readable-stream/duplex.js' in '/Users/zeke/.config/yarn/global/node_modules/stream-browserify'
 @ /Users/zeke/.config/yarn/global/~/stream-browserify/index.js 30:16-52
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/browser-stdout/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/stream-browserify/index.js
Module not found: Error: Can't resolve 'readable-stream/transform.js' in '/Users/zeke/.config/yarn/global/node_modules/stream-browserify'
 @ /Users/zeke/.config/yarn/global/~/stream-browserify/index.js 31:19-58
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/browser-stdout/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /Users/zeke/.config/yarn/global/~/stream-browserify/index.js
Module not found: Error: Can't resolve 'readable-stream/passthrough.js' in '/Users/zeke/.config/yarn/global/node_modules/stream-browserify'
 @ /Users/zeke/.config/yarn/global/~/stream-browserify/index.js 32:21-62
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/browser-stdout/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha

ERROR in /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '/private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/node_modules/mkdirp'
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mkdirp/index.js 2:9-22
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/reporters/xunit.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/reporters/index.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/lib/mocha.js
 @ /private/var/folders/nj/9554mvgj07xdh61jbyhkbtq80000gn/T/package-size-jy2zbwpuhoh3yccv7vi/~/mocha/browser-entry.js
 @ multi mocha
    at /Users/zeke/.config/yarn/global/node_modules/package-size/lib/index.js:114:11
    at next (native)
    at onFulfilled (/Users/zeke/.config/yarn/global/node_modules/co/index.js:65:19)

```

**Comment by zeke** [comment]
```
❯ package-size -v
1.1.1
```

**Comment by egoist** [comment]
hmm why do you want to see the bundle size of mocha? you will never use it in browser I guess and it only supports packages that can be used in browser.

**Comment by zeke** [comment]
Fair enough.. I just typed the first module name that came to mind. Maybe a more helpful error message would be good here.. something like "This doesn't appear to be a browser-friendly module"

**Comment by ChenYangShao** [comment]
Error:  Can't resolve 'fs': 
```js
// webpack.config.js
    node: {
      fs: 'empty'
    }
```
Error : (Critical dependency &&  /growl.js
Module not found: Error: Can't resolve 'child_process' )  How did you resolve this issure

**Comment by egoist** [comment]
@ChenYangShao this is for browser libs, why does it require `fs`?
